/**
* Author:       Ben Edwards
* Date:         2015-11-10
* Description:  Wrapper class to hold details for a Xero Address
**/
public class XeroAddress {
	
	public String AddressType;	
	public String AddressLine1;
	public String AddressLine2;
	public String AddressLine3;
	public String AddressLine4;
	public String City;
	public String Region;
	public String PostalCode;
	public String Country;
	public String AttentionTo;
	
}